### ISSUE TITLE
NGINX - 502 Bad Gateway

### ISSUE THREAD

**Issue by imudryy** [lunarok/htpc_ynh#1]
Hello there lunarok, 

Thanks for building the port of HTPC to Yunohost. However, recently I've ran into an issue with HTPC on YNH. 

After having a clean installation of Yunohost and installing HTPC from this Git repository, I get 502 Bad Gateway error. Nginx logs show the following error

2015/03/14 12:52:22 [error] 16041#0: *917 connect() failed (111: Connection refused) while connecting to upstream, client: MYHOMEIP, server: HOSTNAME, request: "GET /htpc/
HTTP/1.1", upstream: "http://127.0.0.1:8085/htpc/", host: "HOSTNAME", referrer: "https://HOSTNAME/yunohost/admin/"

Could you please help me with what can be causing this issue? Perhaps some changes with NGINX?

Thanks a lot for your help!

**Comment by lunarok** [comment]
Hi,

I think more an issue on the HTPC service not starting. I didnt' remember
for this one I made the autoinstall.

Can you check : service htpc status
And the file /etc/init.d/htpc if it's looking to the right directory for
htpc app

2015-03-14 12:58 GMT+01:00 imudryy <notifications@github.com>:
